name: Enable Auto Merge
on:
  pull_request_target:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Approve dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.0
        with:
          target: minor # includes patch updates!
          github-token: ${{ secrets.DCXP_DEPENDABOT_PAT }}
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{ secrets.DCXP_DEPENDABOT_PAT }}
          allowed-author: "dependabot[bot]"
          merge-method: SQUASH
