name: Build DCXP Gradle Project
on: [ push ]
env:
  CI: true
jobs:
  build-gradle-project:
    name: Build & Test Gradle Project
    #if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: glav/chuck-norris-quote@v1.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Gradle Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper

      - name: Gradle check
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: assemble --scan
          gradle-build-scan-report: true
  publish-to-maven:
    name: Push maven packages
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-gradle-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: glav/chuck-norris-quote@v1.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: '1.0.${{github.run_number}}'
      - name: Setup Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
      - name: Gradle publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}