name: Build DCXP Gradle Project
on: [ push ]
env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-gradle-project:
    name: Build & Test Gradle Project
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5

      - uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check Mac Build
        uses: gradle/gradle-build-action@v2.3.3
        if: matrix.os == 'macOS-latest'
        with:
          arguments: checkMac --scan

      - name: Check Linux Build
        uses: gradle/gradle-build-action@v2.3.3
        if: matrix.os == 'ubuntu-latest'
        with:
          arguments: checkLinux --scan

      - name: Check Windows Build
        uses: gradle/gradle-build-action@v2.3.3
        if: matrix.os == 'windows-latest'
        with:
          arguments: checkWindows --scan

  publish-to-maven:
    name: Push maven packages
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-gradle-project
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5
      - uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish Mac Artifacts
        uses: gradle/gradle-build-action@v2.3.3
        if: matrix.os == 'macOS-latest'
        with:
          arguments: publishMac

      - name: Publish Linux Artifacts
        uses: gradle/gradle-build-action@v2.3.3
        if: matrix.os == 'ubuntu-latest'
        with:
          arguments: publishLinux

      - name: Publish Windows Artifacts
        uses: gradle/gradle-build-action@v2.3.3
        if: matrix.os == 'windows-latest'
        with:
          arguments: publishWindows
