name: Build DCXP Gradle Project
on: [ push ]
env:
  CI: true
jobs:
  build-gradle-project:
    name: Build & Test Gradle Project
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: glav/chuck-norris-quote@v1.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Gradle Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper

      - name: Check Mac Build
        uses: burrunan/gradle-cache-action@v1
        if: matrix.os == 'macOS-latest'
        with:
          arguments: checkMac --scan
          gradle-build-scan-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Linux Build
        uses: burrunan/gradle-cache-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          arguments: checkLinux --scan
          gradle-build-scan-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Windows Build
        uses: burrunan/gradle-cache-action@v1
        if: matrix.os == 'windows-latest'
        with:
          arguments: checkWindows --scan
          gradle-build-scan-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-maven:
    name: Push maven packages
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build-gradle-project
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: glav/chuck-norris-quote@v1.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Setup Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
      - name: Gradle publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Mac Artifacts
        uses: burrunan/gradle-cache-action@v1
        if: matrix.os == 'macOS-latest'
        with:
          arguments: publishMac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Linux Artifacts
        uses: burrunan/gradle-cache-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          arguments: publishLinux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Windows Artifacts
        uses: burrunan/gradle-cache-action@v1
        if: matrix.os == 'windows-latest'
        with:
          arguments: publishWindows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}