name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Setup Gradle Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1