name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.18
        with:
          target-branch: update-gradle
          repo-token: ${{ secrets.DCXP_DEPENDABOT_PAT }}
